name: Smartsheet Synchronization

on:
  schedule:
    - cron: "0 * * * *" # Runs hourly
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13.1"

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Synchronization Script
      env:
        SMARTSHEET_API_KEY: ${{ secrets.SMARTSHEET_API_KEY }}
        SOURCE_SHEET_ID: ${{ secrets.SOURCE_SHEET_ID }}
        TARGET_SHEET_ID: ${{ secrets.TARGET_SHEET_ID }}

      run: python ./'Locator Sheets'/sync_sheet.py

    - name: Run Second Synchronization Step
      env:
        SMARTSHEET_API_KEY: ${{ secrets.SMARTSHEET_API_KEY }}
        SOURCE_SHEET_ID: ${{ secrets.SOURCE_SHEET_ID }}
        Smartsheet_Target_Sheet_ID_Martin: ${{ secrets.Smartsheet_Target_Sheet_ID_Martin }}

      run: python ./'Locator Sheets'/sync_sheet_martin.py

    - name: Run Third Synchronization Step
      env:
        SMARTSHEET_API_KEY: ${{ secrets.SMARTSHEET_API_KEY }}
        SOURCE_SHEET_ID: ${{ secrets.SOURCE_SHEET_ID }}
        Smartsheet_Target_Sheet_ID_Frank: ${{ secrets. Smartsheet_Target_Sheet_ID_Frank}}

      run: python ./'Locator Sheets'/sync_sheet_frank.py

    - name: Run Angel Garays Workflow Step
      env:
        SMARTSHEET_API_KEY: ${{ secrets.SMARTSHEET_API_KEY }}
        SOURCE_SHEET_ID: ${{ secrets.SOURCE_SHEET_LAREDO_ID }}
        Smartsheet_Target_Sheet_ID_Frank: ${{ secrets. Smartsheet_Target_Sheet_ID_Angel}}
        
      run: python ./'Locator Sheets'/sync_sheet_angel.py 

    - name: Run Alfredo Lopez Workflow Step
    env:
      SMARTSHEET_API_KEY: ${{ secrets.SMARTSHEET_API_KEY }}
      SOURCE_SHEET_ID: ${{ secrets.SOURCE_SHEET_ID }}
      Smartsheet_Target_Sheet_ID_Frank: ${{ secrets. SMARTSHEET_TARGET_SHEET_ID_ALFREDO }}

     run: python ./'Locator Sheets'/sync_sheet_alfredo.py
     