name: Smartsheet Synchronization

on:
  schedule:
    - cron: "0 * * * *" # Runs hourly
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13.1"

    - name: Install Dependencies
      run: pip install smartsheet-python-sdk

    - name: Run Synchronization Script
      env:
        API_KEY: ${{ secrets.SMARTSHEET_API_KEY }}
      run: python sync_sheets.py